### ISSUE TITLE
Migrate from Heroku as it isn't free now

### ISSUE THREAD

**Issue by gupta-ji6** [scriptified/scriptified-cms#6]
Heroku recently announced that it's not a freemium service anymore. Read more details in [this](https://blog.heroku.com/next-chapter) blog post.

To prevent disruption to our Scriptified CMS using free plan, we will need to upgrade from a free plan to a paid plan before November 28, 2022.

**Comment by gupta-ji6** [comment]
This could be a potential start - https://fly.io/launch/heroku

Also found this guide - [Migrating Heroku Database Apps to Fly](https://fly.io/blog/migrating-heroku-database-apps-to-fly/)

**Comment by gupta-ji6** [comment]
https://railway.app/ also seems like a good option. I created an account on both and saved it on our account.

cc: @prateek3255

**Comment by prateek3255** [comment]
Can also consider getting rid of CMS and using notion as a CMS with something like:
https://usenotioncms.com/

**Comment by prateek3255** [comment]
Probably not a good idea because the notion API is not as structured as we have with Strapi, we'll need to create wrappers to parse the data anyways

**Comment by gupta-ji6** [comment]
Closing this as we have successfully migrated from Heroku to [Railway](https://railway.app) today.
